project:
  type: book

lang: en

execute:
  freeze: auto
  echo: false
  warning: false

book:
  title: "Agentic AI"
  subtitle: ""
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay
  page-footer:
    left: |
      Â© [Jan Kirenz](https://www.kirenz.com/), 2025
  
  chapters:
    - index.qmd
    - part: "Preparation"
      chapters:
        - accounts.qmd
        - windows-setup.qmd
        - mac-setup.qmd
        - mssql-vscode.qmd
        - mssql-connection.qmd
    # - part: "Agentic AI"
    #   chapters:
    #     - agentic-ai.qmd
    # - part: "Gradio"
    #   chapters:
    #     - gradio.qmd        


number-sections: true

format:
  html:
    toc: true
    theme: cosmo
    css: theme.scss
    code-copy: true
    highlight-style: github
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple
    include-in-header:
      text: |
        <style>
        .cmd-explain {
          font-weight: 600;
          margin-top: 1rem;
        }
        </style>
